version: '3.4'

networks:
    mediatrexample:
        driver: bridge

services:
    pgsql_image:
        image: postgres:latest
        container_name: postgersql_db
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123456"
            POSTGRES_DB: "ecommerce"
        ports:
            - 5432:5432
        networks:
            - mediatrexample

    redis_image:
        image: 'redis:latest'
        container_name: redis_db
        restart: always
        environment:
            - REDIS_PASSWORD=RRnFPZ93tjBHB9W62p
            - REDIS_PORT=6379
        ports:
            - '6379:6379'
        command: [ "redis-server" ]
        networks:
            - mediatrexample

    mediatrexample.api:
        image: ${DOCKER_REGISTRY-}mediatrexampleapi
        container_name: mediatr_example
        depends_on:
            - pgsql_image
            - redis_image
        build:
            context: .
            dockerfile: MediatrExample.API/Dockerfile
        networks:
            - mediatrexample
        links:
            - pgsql_image
            - redis_image
        environment:
            - CONNECTIONSTRINGS__NpgSQLConnection=User ID=postgres;Password=123456;Host=pgsql_image;Port=5432;Database=ecommerce
            - Redis__Host=redis_image
            - Redis__Port=6379
            - Redis__Password=RRnFPZ93tjBHB9W62p
