version: '3.4'

networks:
    mediatrexample:
        driver: bridge
    elk_stack:
        driver: bridge

services:
    pgsql_image:
        image: postgres:latest
        container_name: postgersql_db
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123456"
            POSTGRES_DB: "ecommerce"
        ports:
            - 5432:5432
        networks:
            - mediatrexample

    redis_image:
        image: 'redis:latest'
        container_name: redis_db
        restart: always
        environment:
            - REDIS_PASSWORD=RRnFPZ93tjBHB9W62p
            - REDIS_PORT=6379
        ports:
            - '6379:6379'
        command: [ "redis-server" ]
        networks:
            - mediatrexample

    elastic_image:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        container_name: elk_elastic
        environment:
            - XPACK_SECURITY_ENABLED=true
            - discovery.type=single-node
            - ELASTIC_PASSWORD=DkIedPPSCb
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        networks:
            - elk_stack
        ports:
            - 9200:9200 

    kibana_image:
        container_name: elk_kibana
        image: docker.elastic.co/kibana/kibana:7.5.2
        environment:
            - ELASTICSEARCH_URL=http://elastic_image:9200
            - ELASTICSEARCH_HOSTS=http://elastic_image:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=DkIedPPSCb
        networks:
            - elk_stack
        depends_on:
            - elastic_image
        links:
            - elastic_image   
        ports:
            - 5601:5601

    mediatrexample.api:
        image: ${DOCKER_REGISTRY-}mediatrexampleapi
        container_name: mediatr_example
        depends_on:
            - pgsql_image
            - redis_image
        build:
            context: .
            dockerfile: MediatrExample.API/Dockerfile
        networks:
            - mediatrexample
        links:
            - pgsql_image
            - redis_image
        environment:
            - CONNECTIONSTRINGS__NpgSQLConnection=User ID=postgres;Password=123456;Host=pgsql_image;Port=5432;Database=ecommerce
            - Redis__Host=redis_image
            - Redis__Port=6379
            - Redis__Password=RRnFPZ93tjBHB9W62p
